create table if not exists crtech_offers_lang
(
    LID char(2) not null,
    CURRENCY char(3) not null,
    primary key (LID)
    );

create table if not exists crtech_offers_fuser
(
    ID int not null auto_increment,
    DATE_INSERT datetime not null,
    DATE_UPDATE datetime not null,
    USER_ID INT NULL,
    CODE varchar(32),
    primary key (ID),
    index IX_USER_ID(USER_ID),
    index IX_CODE(CODE(32))
    );

create table if not exists crtech_offers_basket
(
    ID int not null auto_increment,
    FUSER_ID int not null,
    ORDER_ID int null,
    PRODUCT_ID int not null,
    PRODUCT_PRICE_ID int null,
    PRICE_TYPE_ID int null,
    PRICE decimal(18, 4) not null,
    CURRENCY char(3) not null,
    BASE_PRICE decimal(18, 4) null,
    VAT_INCLUDED char(1) not null default 'Y',
    DATE_INSERT datetime not null,
    DATE_UPDATE datetime not null,
    DATE_REFRESH datetime null,
    WEIGHT double(18, 2) null,
    QUANTITY double(18, 4) not null default '0',
    LID char(2) not null,
    DELAY char(1) not null default 'N',
    NAME varchar(255) not null,
    CAN_BUY char(1) not null default 'Y',
    MARKING_CODE_GROUP varchar(100) null,
    MODULE varchar(100) null,
    CALLBACK_FUNC varchar(100) null,
    NOTES varchar(250) null,
    ORDER_CALLBACK_FUNC varchar(100) null,
    DETAIL_PAGE_URL varchar(250) null,
    DISCOUNT_PRICE decimal(18,4) not null,
    CANCEL_CALLBACK_FUNC varchar(100) null,
    PAY_CALLBACK_FUNC varchar(100) null,
    PRODUCT_PROVIDER_CLASS varchar(100) null,
    CATALOG_XML_ID varchar(100) null,
    PRODUCT_XML_ID varchar(100) null,
    DISCOUNT_NAME varchar(255) null,
    DISCOUNT_VALUE char(32) null,
    DISCOUNT_COUPON char(32) null,
    VAT_RATE DECIMAL(18, 4) NULL default '0.00',
    SUBSCRIBE char(1) not null default 'N',
    DEDUCTED char(1) not null default 'N',
    RESERVED char(1) not null default 'N',
    BARCODE_MULTI char(1) not null default 'N',
    RESERVE_QUANTITY double null,
    CUSTOM_PRICE char(1) not null default 'N',
    DIMENSIONS varchar(255) null,
    TYPE int(11) null,
    SET_PARENT_ID int(11) null,
    MEASURE_CODE INT(11) NULL,
    MEASURE_NAME varchar(50) null,
    RECOMMENDATION varchar(40) null,
    XML_ID varchar(255) null,
    SORT INT(11) not null default '100',
    primary key (ID),
    index IXS_BASKET_LID(LID),
    index IXS_BASKET_USER_ID(FUSER_ID),
    index IXS_BASKET_ORDER_ID(ORDER_ID),
    index IXS_BASKET_PRODUCT_ID(PRODUCT_ID),
    index IXS_BASKET_PRODUCT_PRICE_ID(PRODUCT_PRICE_ID),
    index IXS_SBAS_XML_ID(PRODUCT_XML_ID, CATALOG_XML_ID),
    index IXS_BASKET_DATE_INSERT(DATE_INSERT),
    index IXS_BASKET_SET_PARENT_ID(SET_PARENT_ID)
    );

create table if not exists crtech_offers_basket_props
(
    ID int not null auto_increment,
    BASKET_ID int not null,
    NAME varchar(255) not null,
    VALUE varchar(255) null,
    CODE varchar(255) null,
    SORT int not null default '100',
    XML_ID varchar(255) null,
    primary key (ID),
    index IXS_BASKET_PROPS_BASKET(BASKET_ID),
    index IXS_BASKET_PROPS_CODE(CODE)
    );

create table if not exists crtech_offers_order
(
    ID int not null auto_increment,
    LID char(2) not null,
    PERSON_TYPE_ID int not null,
    PAYED char(1) not null default 'N',
    DATE_PAYED datetime null,
    EMP_PAYED_ID int null,
    CANCELED char(1) not null default 'N',
    DATE_CANCELED datetime null,
    EMP_CANCELED_ID int null,
    REASON_CANCELED varchar(255) null,
    STATUS_ID varchar(2) not null,
    DATE_STATUS datetime not null,
    EMP_STATUS_ID int null,
    PRICE_DELIVERY decimal(18,4) NOT NULL DEFAULT '0.0000',
    PRICE_PAYMENT decimal(18,4) NOT NULL DEFAULT '0.0000',
    ALLOW_DELIVERY char(1) not null default 'N',
    DATE_ALLOW_DELIVERY datetime null,
    EMP_ALLOW_DELIVERY_ID int null,
    DEDUCTED char(1) not null default 'N',
    DATE_DEDUCTED datetime null,
    EMP_DEDUCTED_ID int null,
    REASON_UNDO_DEDUCTED varchar(255) null,
    MARKED char(1) not null default 'N',
    DATE_MARKED datetime null,
    EMP_MARKED_ID int null,
    REASON_MARKED varchar(255) null,
    RESERVED char(1) not null default 'N',
    PRICE decimal(18, 4) not null,
    CURRENCY char(3) not null,
    DISCOUNT_VALUE decimal(18,4) NOT NULL DEFAULT '0.0000',
    USER_ID int not null,
    PAY_SYSTEM_ID int null,
    DELIVERY_ID varchar(50) null,
    DATE_INSERT datetime not null,
    DATE_UPDATE datetime not null,
    USER_DESCRIPTION varchar(2000) null,
    ADDITIONAL_INFO varchar(255) null,
    PS_STATUS char(1) null,
    PS_STATUS_CODE char(5) null,
    PS_STATUS_DESCRIPTION varchar(250) null,
    PS_STATUS_MESSAGE varchar(250) null,
    PS_SUM decimal(18,2) null,
    PS_CURRENCY char(3) null,
    PS_RESPONSE_DATE datetime null,
    COMMENTS text null,
    TAX_VALUE decimal(18,2) not null default '0.00',
    STAT_GID varchar(255) null,
    SUM_PAID decimal(18,2) not null default '0',
    IS_RECURRING char(1) not null default 'N',
    RECURRING_ID int null,
    PAY_VOUCHER_NUM varchar(20) null,
    PAY_VOUCHER_DATE date null,
    LOCKED_BY int null,
    DATE_LOCK datetime null,
    RECOUNT_FLAG char(1) not null default 'Y',
    AFFILIATE_ID int null,
    DELIVERY_DOC_NUM varchar(20) null,
    DELIVERY_DOC_DATE date null,
    UPDATED_1C CHAR(1) NOT NULL DEFAULT 'N',
    STORE_ID int null,
    ORDER_TOPIC varchar(255) null,
    CREATED_BY int(11) null,
    RESPONSIBLE_ID int(11) null,
    COMPANY_ID int(11) null,
    DATE_PAY_BEFORE datetime null,
    DATE_BILL datetime null,
    ACCOUNT_NUMBER varchar(100) null,
    TRACKING_NUMBER varchar(255) NULL,
    XML_ID varchar(255) null,
    ID_1C varchar(36) null,
    VERSION_1C varchar(15) null,
    VERSION INT(11) not null default '0',
    EXTERNAL_ORDER char(1) not null default 'N',
    RUNNING char(1) not null default 'N',
    BX_USER_ID varchar(32) null,
    SEARCH_CONTENT mediumtext null,
    IS_SYNC_B24 CHAR(1) not null default 'N',
    primary key (ID),
    index IXS_ORDER_PERSON_TYPE_ID(PERSON_TYPE_ID),
    index IXS_ORDER_STATUS_ID(STATUS_ID),
    index IXS_ORDER_REC_ID(RECURRING_ID),
    index IX_SOO_AFFILIATE_ID(AFFILIATE_ID),
    index IXS_ORDER_UPDATED_1C(UPDATED_1C),
    index IXS_SALE_COUNT(USER_ID,LID,PAYED,CANCELED),
    index IXS_DATE_UPDATE(DATE_UPDATE),
    index IXS_XML_ID(XML_ID),
    index IXS_ID_1C(ID_1C),
    index IX_BSO_DATE_ALLOW_DELIVERY(DATE_ALLOW_DELIVERY),
    index IX_BSO_ALLOW_DELIVERY(ALLOW_DELIVERY),
    index IX_BSO_DATE_CANCELED(DATE_CANCELED),
    index IX_BSO_CANCELED(CANCELED),
    index IX_BSO_DATE_PAYED(DATE_PAYED),
    index IX_BSO_DATE_INSERT(DATE_INSERT),
    index IX_BSO_DATE_PAY_BEFORE(DATE_PAY_BEFORE),
    unique IXS_ACCOUNT_NUMBER(ACCOUNT_NUMBER)
    );

create table if not exists crtech_offers_order_archive(
                                                   ID int NOT NULL AUTO_INCREMENT,
                                                   LID char(2) NOT NULL,
    ORDER_ID int NOT NULL,
    ACCOUNT_NUMBER varchar(100) NOT NULL,
    DATE_INSERT datetime NOT NULL,
    PERSON_TYPE_ID int NOT NULL,
    USER_ID int NOT NULL,
    STATUS_ID varchar(2) NOT NULL,
    PAYED char(1) NOT NULL DEFAULT 'N',
    DEDUCTED char(1) NOT NULL DEFAULT 'N',
    CANCELED char(1) NOT NULL DEFAULT 'N',
    PRICE decimal(18, 4) NOT NULL,
    SUM_PAID decimal(18,2) NULL,
    CURRENCY char(3) NOT NULL,
    XML_ID varchar(255) NULL,
    ID_1C varchar(36) NULL,
    ORDER_DATA mediumtext NULL,
    RESPONSIBLE_ID int(11) NULL,
    COMPANY_ID int(11) NULL,
    VERSION int NOT NULL,
    DATE_ARCHIVED datetime NOT NULL,
    primary key (ID),
    index IXS_USER_ID(USER_ID),
    index IXS_STATUS_ID(STATUS_ID),
    index IXS_DATE_INSERT(DATE_INSERT),
    index IXS_DATE_ARCHIVED(DATE_ARCHIVED),
    index IXS_XML_ID(XML_ID),
    index IXS_ID_1C(ID_1C),
    index IXS_RESPONSIBLE_ID(RESPONSIBLE_ID),
    index IXS_COMPANY_ID(COMPANY_ID),
    index IXS_ORDER_ID(ORDER_ID),
    index IXS_ACCOUNT_NUMBER(ACCOUNT_NUMBER)
    );

create table if not exists crtech_offers_order_archive_packed(
                                                          ORDER_ARCHIVE_ID int NOT NULL,
                                                          ORDER_DATA mediumtext NULL,
                                                          PRIMARY KEY (ORDER_ARCHIVE_ID)
    );

create table if not exists crtech_offers_basket_archive(
                                                    ID int NOT NULL AUTO_INCREMENT,
                                                    ARCHIVE_ID int NOT NULL,
                                                    PRODUCT_ID int NOT NULL,
                                                    PRODUCT_PRICE_ID int NULL,
                                                    NAME varchar(255) NOT NULL,
    PRICE decimal(18, 4) NULL,
    CURRENCY char(3) NULL,
    QUANTITY double(18, 4) NULL,
    WEIGHT double(18, 4) NULL,
    DATE_INSERT datetime NOT NULL,
    MODULE varchar(100) NULL,
    PRODUCT_XML_ID varchar(100) NULL,
    TYPE int(11) NULL,
    SET_PARENT_ID int(11) NULL,
    MEASURE_CODE int(11) NULL,
    MEASURE_NAME varchar(50),
    BASKET_DATA mediumtext NULL,
    primary key (ID),
    index IXS_PRODUCT_ID(PRODUCT_ID),
    index IXS_ARCHIVE_ID(ARCHIVE_ID)
    );

create table if not exists crtech_offers_basket_archive_packed(
                                                           BASKET_ARCHIVE_ID int NOT NULL,
                                                           BASKET_DATA mediumtext NULL,
                                                           PRIMARY KEY (BASKET_ARCHIVE_ID)
    );