drop table if exists crtech_offers_lang;
drop table if exists crtech_offers_fuser;
drop table if exists crtech_offers_basket;
drop table if exists crtech_offers_basket_props;
drop table if exists crtech_offers_order;
drop table if exists crtech_offers_order_archive;
drop table if exists crtech_offers_order_archive_packed;
drop table if exists crtech_offers_basket_archive;
drop table if exists crtech_offers_basket_archive_packed;